apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: isindir-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://isindir.github.io/sops-secrets-operator

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-controller
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sops-secrets-operator
      version: ">=0.19.0"
      sourceRef:
        kind: HelmRepository
        name: isindir-charts
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3