version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - app-network
  db:
    image: postgres:16-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    user: "1001:1001"

networks:
  app-network:
    driver: bridge