# values.yaml
app:
  replicaCount: 1
  image:
    repository: dbunt1tled/test_docker
    tag: v1.0.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  secrets:
    db_dsn: postgresql://postgres:postgres@inwebapp-postgres:5432/postgres?sslmode=disable
  env:
    APP_ENV: "production"
    LOG_LEVEL: "info"

ingress:
  enabled: true
  host: app.inwebapp.local
  className: nginx

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    type: "ClusterIP"
    port: 5432
    targetPort: 5432
  secrets:
    db_port: 5432
    db_user: postgres
    db_password: postgres
    db_db: postgres
  port: 5432
  user: postgres
  password: postgres
  db: postgres
  persistence:
    enabled: true
    size: "1Gi"
    storageClass: ""
    accessMode: "ReadWriteOnce"
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"

prometheus:
  enabled: true
  #namespaceOverride: monitoring
  serviceMonitor:
    enabled: true
    additionalServiceMonitors:
      - name: inwebapp-app
        selector:
          matchLabels:
            app: inwebapp-app
        endpoints:
          - port: http
            path: /metrics
            interval: 15s
            scheme: http
            tlsConfig:
              insecureSkipVerify: true
  grafana:
    enabled: false
  server:
    ingress:
      enabled: false
      ingressClassName: nginx
      hosts:
        - prometheus.inwebapp.local
      paths:
        - /
      tls: []

loki-stack:
  #namespaceOverride: logging
  grafana:
    enabled: false
  promtail:
    enabled: true

ingress-nginx:
  controller:
    admissionWebhooks:
      enabled: true
    namespaceOverride: ingress-nginx

grafana:
  #namespaceOverride: monitoring
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    host: grafana.inwebapp.local
    className: nginx
    ingressClassName: nginx
    paths:
      - /
    tls: []