name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run go
        run: echo "Hello from GitHub Actions 🚀"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Build application
        run: go build -o test_docker main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_docker
          path: test_docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test_docker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/test_docker:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/test_docker:${{ github.ref_name }}
