name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run go
        run: echo "Hello from GitHub Actions 🚀"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Build application
        run: go build -o docker_test main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker_test
          path: docker_test